### ISSUE TITLE
Validate favorites before adding to db. Aka does that user already have the movie stored as favorites. There should be no duplicates.

### ISSUE THREAD

**Issue by Jstewart3313** [Jessica-Erickson/movie-tracker#8]

**Comment by Jstewart3313** [comment]
- [ ] Did we test?

**Comment by Jessica-Erickson** [comment]
- [ ] When user signs in, get the movies from favorites and unshift them into movies array in state, if they aren't already there. 
- [ ] if their favorite is still in the movies array, toggle is favorited to true
